# Generated by Django 5.0.2 on 2024-02-17 20:08
from django.contrib.auth.models import Group
from django.db import migrations


def initialize_data(apps, schema_editor):
    Group.objects.get_or_create(name='ADMIN')
    Group.objects.get_or_create(name='OPERATOR')


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initialize_data),
    ]
