version: '3.8'
services:
  django-example-postgresql:
    container_name: django-example-postgresql
    image: postgres:14.5
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - django_example-net
#  django-example-rabbit-stomp:
#    container_name: django-example-rabbit-stomp
#    image: django-example-rabbit-stomp
#    build:
#      dockerfile: rabbitmq.Dockerfile
#    ports:
#      - "15672:15672"
#      - "5672:5672"
#      - "61613:61613"
#    env_file: .env
#    networks:
#      - django_example-net

networks:
  django_example-net: