version: '3.8'
services:
  django-example-postgresql:
    container_name: django-example-postgresql
    image: postgres:14.5
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - django_example-net

  django-example-redis:
    container_name: django-example-redis
    image: redis:7.2.4
    env_file: .env
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - django_example-net

networks:
  django_example-net: