# Generated by Django 5.0.2 on 2024-02-17 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='isWatched2',
            field=models.BooleanField(default=False),
        ),
    ]
