# Generated by Django 5.0.2 on 2024-02-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('summary', models.TextField()),
                ('isWatched', models.BooleanField(default=False)),
            ],
        ),
    ]
