# Generated by Django 5.0.2 on 2024-02-17 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_iswatched2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='isWatched2',
        ),
    ]
